Fix pseudo-code
bottom-software-foundation/spec pull request #1
Opened 2021-01-20 23:24 UTC by nihaals

2021-01-22 03:12 UTC, numbermaniac requested changes

2021-01-22 03:12 UTC, numbermaniac commented on README.md
>                  v = v - 200
```suggestion
                v = v - 50
```

2021-01-22 03:12 UTC, numbermaniac commented on README.md
>                  v = v - 200
```suggestion
                v = v - 10
```

2021-01-22 03:12 UTC, numbermaniac commented on README.md
>                  v = v - 200
```suggestion
                v = v - 5
```

2021-01-22 03:12 UTC, numbermaniac commented on README.md
>                  o.append(🫂)
This one needs to be changed too; and the line below changed to `v - 1`.

2021-01-22 03:12 UTC, numbermaniac commented on README.md
> +                o.append(,)
Comma is for the value 1.
5 should be the 🥺 face according to the table.

2021-01-23 11:10 UTC, nihaals commented
Oops, I didn't look in-depth, I just assumed it was only the emoji that were wrong

2021-01-23 11:43 UTC, numbermaniac approved these changes

2021-01-23 21:56 UTC, kaylynn234 commented
I'll do this locally.

2021-01-23 21:56 UTC, closed without merging